# numpy array tutorial


In [1]:
!pip install pandas


In [2]:
import numpy as np
#marks=np.array([[1,278787,4,r,3]],np.int64) we can not store mix data types data in numpy array
marks=np.array([[1,278787,4,3]]) #int64 is the size of a single digit in array
print(marks)                              #[] single array/one dimentional 
                                          #[[]] 2d/two dimentinal array

[[     1 278787      4      3]]


In [2]:
marks[0,1]              #two dimentional array element 
                        #marks[0] single array element location   

278787

In [3]:
marks.shape  #this python command will show the dimention of the array where 1=rows, 4= columns

(1, 4)

In [4]:
marks.dtype           #will show the data type of the array

dtype('int64')

# list array


In [5]:
listarray=np.array([[1,2,3],['e',4,3],['f',5,2]]) #in this array we can store multiple data type element
print(listarray)

[['1' '2' '3']
 ['e' '4' '3']
 ['f' '5' '2']]


In [6]:
listarray.shape

(3, 3)

In [7]:
listarray[0,1]

'2'

In [8]:
zeroarray=np.zeros((2,5))   #this code of line will create zero array 

In [9]:
zeroarray.shape

(2, 5)

In [10]:
zeroarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## numpy array

In [11]:
rangarray=np.arange(15) #this will create a numpy array haveing range n-1

In [12]:
rangarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## linspace


In [13]:
equal_digitspace=np.linspace(1,10,5) #this linspace funtion will gives us equal spaces numbers between 1 to 10

In [14]:
equal_digitspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

##numpay array

In [15]:
myarray=np.arange(55)

In [16]:
myarray


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [17]:
myarray.shape

(55,)

##now we can change the shape of the  above array

In [18]:
myarray.reshape(5,11)       #here we have converted (55,)=(5(rows),(11(columns)))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

## numpy axis

In [19]:
array=np.arange(15)

In [20]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
narray=array.reshape(3,5)


In [22]:
narray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## now to sum the elements of the row and column of the array

In [23]:
narray.sum(axis=0)          #where axis=0 represent columns in array 

array([15, 18, 21, 24, 27])

In [24]:
narray.sum(axis=1)          #where axis=1  [[[axis=1 represent columns in array 

array([10, 35, 60])

##array transpose

In [25]:
narray.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [26]:
a=narray.flat

In [27]:
for items in a:
    print(items)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [28]:
d_array=np.array(a)   #convertion back form flat to numpy array


In [29]:
d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
d_array.nbytes   #size than by this array

60

In [31]:
d_array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
d_array.ravel()  ##this is an important function used to convert 2 diemton array into single line

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
one_array=np.array([1,0,3,41,5])

In [34]:
one_array.argmax() #this funtion will show you the position of max entry in you array.

3

In [35]:
one_array.argmin() 

1

In [36]:
one_array.argsort()             ##this funtion is used to display the postion of arrays element according to there 

array([1, 0, 2, 4, 3], dtype=int64)

In [37]:
d_array.argsort(axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

In [38]:
d_array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
new_arr=np.arange(9)

In [40]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
new_array=new_arr.reshape(3,3)

In [42]:
new_arr2=np.array([[0, 6, 2],
       [3, 0, 5],
       [6, 7, 3]])

In [44]:
new_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## matrixs operations

In [45]:
new_arr2

array([[0, 6, 2],
       [3, 0, 5],
       [6, 7, 3]])

In [46]:
new_array+new_arr2

array([[ 0,  7,  4],
       [ 6,  4, 10],
       [12, 14, 11]])

## matrix multiplication

In [47]:
new_array*new_arr2            ##there is problem with this fucntion 

array([[ 0,  6,  4],
       [ 9,  0, 25],
       [36, 49, 24]])

In [58]:
new_matrix=np.dot(new_array,new_arr2) ##wow amazing here is the correct fuction for two matrix multiplicatin
print(new_matrix)

[[15 14 11]
 [42 53 41]
 [69 92 71]]


##square_root of martrix elements

In [53]:
square_new_matrix=np.sqrt(new_matrix)
print(square_new_matrix)

[[3.87298335 3.74165739 3.31662479]
 [6.4807407  7.28010989 6.40312424]
 [8.30662386 9.59166305 8.42614977]]


In [60]:
np.where(new_matrix<50)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 2], dtype=int64))