In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5]
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]

In [3]:
arr=np.array(list)

In [4]:
arr.shape

(5,)

**to make a 2D array


In [5]:
_2darr =np.array([list,list1,list2])

In [6]:
_2darr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [7]:
_2darr[::]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [8]:
_2darr[:,2]

array([3, 3, 3])

In [9]:
_2darr[:,4]

array([5, 5, 5])

**to print array in reverse order

In [10]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [11]:
_2darr[1:,2:] 

array([[3, 4, 5],
       [3, 4, 5]])

In [12]:
_2darr[:,:2]

array([[1, 2],
       [1, 2],
       [1, 2]])

**condition apply to array to return the minimum value in array


In [13]:
arr[arr<2]

array([1])

**to reshape an array structure

In [14]:
_2darr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

*anther way to declare array

In [15]:
np.arange(1,16,1).reshape(5,3)
                          

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [16]:
_2darray2=np.arange(1,16,1).reshape(3,5)

**array multiplication

In [17]:
_2darr*_2darray2

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50],
       [11, 24, 39, 56, 75]])

**to genrate random array element


In [18]:
np.random.randint(10,60,4)

array([49, 10, 25, 19])

In [19]:
np.random.random_sample(3)

array([0.30809374, 0.58455628, 0.88514088])

In [20]:
np.random.randn(10,60,4)

array([[[-2.76853430e+00, -1.30662538e+00, -7.49139311e-01,
         -1.38195064e+00],
        [ 1.16180600e-01, -2.15822545e-01, -5.17666446e-01,
          1.29698738e+00],
        [ 8.58160832e-01,  8.39263407e-01,  4.13364348e-01,
         -3.08033657e-01],
        ...,
        [ 2.96916017e-01,  1.27737581e+00, -2.73403098e-01,
         -1.84290577e-03],
        [-4.00255363e-01,  1.48188305e+00, -8.08445158e-01,
         -1.10865330e+00],
        [ 5.93493301e-01,  1.18502866e+00, -7.22874658e-01,
          5.14703129e-02]],

       [[-7.68975450e-01,  8.09185833e-01,  1.14633474e+00,
         -1.53305445e-01],
        [-1.44681601e+00,  6.58585821e-01, -1.47685656e+00,
          8.37251618e-01],
        [-1.54856718e-01,  2.05092677e+00, -1.64811945e+00,
         -6.33397867e-01],
        ...,
        [-1.45435558e+00, -1.06231808e+00,  2.97476900e-01,
          2.71537273e-01],
        [-9.83697039e-01, -2.27721219e-01, -6.20605676e-01,
         -7.23963975e-01],
        [ 1.912

In [23]:
np.random.randn(5,10) 

array([[-0.55535856,  0.87208392, -1.07080657, -0.27247628,  2.54949818,
         0.49160343,  0.74147792,  0.23542158, -0.13098105, -0.73016636],
       [-0.89779735, -0.94077271,  0.38279611, -0.20729947,  0.15221868,
         1.76276286,  0.0705011 , -0.53234819, -0.39933847,  0.97665974],
       [ 0.17014346, -0.54335744, -0.47213007, -0.04956768,  1.91628165,
        -0.87083438,  0.12018859, -0.06407218,  0.0485962 , -1.21674482],
       [ 0.10503427, -2.01873393, -0.84111777,  0.70187763,  0.638553  ,
         0.5936222 , -0.49450951,  0.76533679, -0.47032995,  1.46972913],
       [ 1.76842407,  1.09880984,  1.60759004,  0.50243775, -0.12260505,
         1.64393163,  1.26826058, -1.7444417 , -0.65542742, -0.84881596]])

In [26]:
np.random.randint(6)  #this will genrate random inter between 0,5

2